services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=blog
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  db_data:

networks:
  app-network:
